import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Wiki Results </title>
        <link 
          href="https://fonts.googleapis.com/css2?family=Your+Font+Family&display=swap" 
          rel="stylesheet"
        />
      </head>
      <body style={{ 
        backgroundColor: 'white',  // Change this color as needed
        margin: 0,
        minHeight: '100vh'
      }}>
        {children}
      </body>
    </html>
  );
}


